channels:
- conda-forge
dependencies:
- python=3.8.3
- pip
- pip:
  - mlflow
  - asyncio==3.4.3
  - cloudpickle==2.1.0
  - dataclasses==0.6
  - psutil==5.9.2
  - scikit-learn==1.2.2
  - threadpoolctl==2.2.0
  - typing-extensions==4.5.0
name: mlflow-env
