base:
  project: dvc_mlpipeline
  random_state: 55
  target_col: quality

data_source:
  local_path: https://raw.githubusercontent.com/tekrajchhetri/mlops/master/dvc/data/red_wine.csv

preprocess:
  dir: data/preprocessed
  preprocessed_file: preprocessed_file.csv

split:
  dir: data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.30

process:
  dir: data/processed

train:
  n_est: 65

model_dir: model



